# script_config.yaml
# Configuration for map dependencies and preprocessing for gem_tracker_maps

trackers:
  - name: Tracker1
    description: Description of Tracker1
    data_source: path_or_url_to_data
    maps:
      - map_name: MapA
        output_file: mapA_output.tif
        dependencies:
          - dependency1
          - dependency2
      - map_name: MapB
        output_file: mapB_output.tif
        dependencies:
          - dependency3
  - name: Tracker2
    description: Description of Tracker2
    data_source: path_or_url_to_data
    maps:
      - map_name: MapC
        output_file: mapC_output.tif
        dependencies:
          - dependency4
          - dependency5
  # ... Add remaining trackers here

maps:
  - name: MapA
    description: Description of MapA
    tracker: Tracker1
    dependencies:
      - dependency1
      - dependency2
  - name: MapB
    description: Description of MapB
    tracker: Tracker1
    dependencies:
      - dependency3
  - name: MapC
    description: Description of MapC
    tracker: Tracker2
    dependencies:
      - dependency4
      - dependency5
  # ... Add remaining maps here

# Example dependency definitions (optional)
dependencies:
  dependency1: path_or_url_to_dependency1
  dependency2: path_or_url_to_dependency2
  dependency3: path_or_url_to_dependency3
  dependency4: path_or_url_to_dependency4
  dependency5: path_or_url_to_dependency5
  # ... Add remaining dependencies here

  